"""Safe Orphan Cleaner.

Scans the entity registry for entries flagged as orphaned by Home
Assistant itself (orphaned_timestamp set - the same signal behind the
official "This entity is currently unavailable and is an orphan..."
frontend warning), checks each one for whether its entity_id has been
reused by a currently LIVE entity, and writes two ready-to-run bash
scripts under <config_path>/safe_orphan_cleaner/ - each line already a
full call to the proven community bash script
(https://community.home-assistant.io/t/6-routines-to-delete-rename-move-devices-entities-and-their-corresponding-registry-entries-data-and-metadata/755476/7):

  safe_orphans_remove.sh      - entity_id not reused anywhere live
  dangerous_orphans_remove.sh - entity_id reused by a live entity
                                 (still safe to remove via -E/registry_id,
                                 just never via -e/entity_id)

Both scripts always use -E (registry_id), which sidesteps the entity_id
collision question entirely - that's *why* the split exists, so you can
choose to run the "dangerous" batch separately/more carefully if you
want, not because it's unsafe on its own.

This integration does not remove anything itself. Real-world testing
showed entity_registry.async_remove() only reliably removes *live*
entities (moving them to deleted_entities) - it does not purge an entry
that's already there, and there's no documented public API that does.
Generating scripts for the proven external tool is more honest than
pretending to have a working "Remove" button.

Service:
  safe_orphan_cleaner.scan
    Re-scans, rewrites both scripts, and returns counts plus the path
    to each script (host_path is what to run: `bash <host_path>`).
"""
from __future__ import annotations

import logging
import os

import voluptuous as vol

from homeassistant.core import HomeAssistant, ServiceCall, SupportsResponse
from homeassistant.helpers import entity_registry as er

DOMAIN = "safe_orphan_cleaner"
_LOGGER = logging.getLogger(__name__)

SERVICE_SCAN = "scan"

CONF_SCRIPT_PATH = "script_path"
CONF_CONFIG_PATH = "config_path"
CONF_BACKUP_DIR = "backup_dir"

DEFAULT_SCRIPT_PATH = "/home/pelle/scripts/ha_delete_device_entity.sh"
DEFAULT_CONFIG_PATH = "/home/pelle/docker/homeassistant/config"
DEFAULT_BACKUP_DIR = "/home/pelle/scripts/backups"

SUBFOLDER = "safe_orphan_cleaner"
SAFE_FILENAME = "safe_orphans_remove.sh"
DANGEROUS_FILENAME = "dangerous_orphans_remove.sh"

CONFIG_SCHEMA = vol.Schema(
    {
        DOMAIN: vol.Schema(
            {
                vol.Optional(CONF_SCRIPT_PATH, default=DEFAULT_SCRIPT_PATH): str,
                vol.Optional(CONF_CONFIG_PATH, default=DEFAULT_CONFIG_PATH): str,
                vol.Optional(CONF_BACKUP_DIR, default=DEFAULT_BACKUP_DIR): str,
            }
        )
    },
    extra=vol.ALLOW_EXTRA,
)


def _deleted_entity_id(deleted_entry) -> str | None:
    """Best-effort extraction of the entity_id from a DeletedRegistryEntry."""
    return getattr(deleted_entry, "entity_id", None)


def _run_scan(hass: HomeAssistant) -> dict:
    """Scan the registry. Returns raw ids split into safe/dangerous."""
    registry = er.async_get(hass)
    live_ids = set(registry.entities.keys())

    safe_ids: list[str] = []
    dangerous_ids: list[str] = []
    skipped_no_entity_id = 0

    for deleted_entry in registry.deleted_entities.values():
        if getattr(deleted_entry, "orphaned_timestamp", None) is None:
            continue

        entity_id = _deleted_entity_id(deleted_entry)
        if entity_id is None:
            skipped_no_entity_id += 1
            continue

        registry_id = getattr(deleted_entry, "id", None)
        if registry_id is None:
            skipped_no_entity_id += 1
            continue

        if entity_id in live_ids:
            dangerous_ids.append(registry_id)
        else:
            safe_ids.append(registry_id)

    return {
        "safe_ids": safe_ids,
        "dangerous_ids": dangerous_ids,
        "skipped_unresolvable": skipped_no_entity_id,
    }


def _write_script_file(hass: HomeAssistant, paths: dict, filename: str, ids: list[str]) -> str:
    """Write a ready-to-run bash script, one -E call per line.

    Returns the HA-internal path written. Also chmods the file world
    readable+executable, since the container and the host user running
    it can be different UIDs across the bind mount.
    """
    rel_path = f"{SUBFOLDER}/{filename}"
    full_path = hass.config.path(rel_path)
    os.makedirs(os.path.dirname(full_path), exist_ok=True)

    with open(full_path, "w", encoding="utf-8") as f:
        f.write("#!/bin/bash\n")
        f.write("# Generated by Safe Orphan Cleaner - review before running.\n")
        f.write("# Intentionally no 'set -e': the underlying script can exit\n")
        f.write("# non-zero on normal paths (e.g. after the orphaned-attributes\n")
        f.write("# N/T/A prompt), which would otherwise abort this loop after\n")
        f.write("# just the first entity.\n\n")
        for reg_id in ids:
            f.write(
                f'sudo {paths[CONF_SCRIPT_PATH]} '
                f'-x {paths[CONF_CONFIG_PATH]} -b {paths[CONF_BACKUP_DIR]} '
                f'-E {reg_id}\n'
            )

    os.chmod(full_path, 0o755)
    return full_path


async def async_setup(hass: HomeAssistant, config: dict) -> bool:
    """Set up the safe_orphan_cleaner scan service."""
    domain_config = config.get(DOMAIN) or {}
    paths = {
        CONF_SCRIPT_PATH: domain_config.get(CONF_SCRIPT_PATH, DEFAULT_SCRIPT_PATH),
        CONF_CONFIG_PATH: domain_config.get(CONF_CONFIG_PATH, DEFAULT_CONFIG_PATH),
        CONF_BACKUP_DIR: domain_config.get(CONF_BACKUP_DIR, DEFAULT_BACKUP_DIR),
    }

    async def handle_scan(call: ServiceCall) -> dict:
        results = await hass.async_add_executor_job(_run_scan, hass)

        await hass.async_add_executor_job(
            _write_script_file, hass, paths, SAFE_FILENAME, results["safe_ids"]
        )
        await hass.async_add_executor_job(
            _write_script_file, hass, paths, DANGEROUS_FILENAME, results["dangerous_ids"]
        )

        # Host-side paths (what you actually run `bash <path>` against),
        # built from the configured config_path - this only coincides
        # with HA's internal /config path for non-container installs.
        safe_host_path = f"{paths[CONF_CONFIG_PATH]}/{SUBFOLDER}/{SAFE_FILENAME}"
        dangerous_host_path = f"{paths[CONF_CONFIG_PATH]}/{SUBFOLDER}/{DANGEROUS_FILENAME}"

        response = {
            "safe_count": len(results["safe_ids"]),
            "dangerous_count": len(results["dangerous_ids"]),
            "skipped_unresolvable": results["skipped_unresolvable"],
            "safe_script": safe_host_path,
            "dangerous_script": dangerous_host_path,
        }

        _LOGGER.info(
            "Safe Orphan Cleaner scan: %d safe, %d dangerous, %d unresolvable - scripts written to %s",
            response["safe_count"],
            response["dangerous_count"],
            response["skipped_unresolvable"],
            SUBFOLDER,
        )
        return response

    hass.services.async_register(
        DOMAIN, SERVICE_SCAN, handle_scan, supports_response=SupportsResponse.ONLY
    )

    return True
